---
- hosts: 127.0.0.1
  remote_user: ansible
  sudo: yes

  tasks:
  - name: install fakeroot
    apt: pkg=fakeroot update_cache=yes
  - name: install google-chrome-stable
    apt: pkg=google-chrome-stable update_cache=yes
  - name: install openssh-server
    apt: pkg=openssh-server update_cache=yes
  - name: install vim
    apt: pkg=vim update_cache=yes
  - name: setup vim
    file: src=/usr/share/vim/vimrc dest=/home/dfn/.vimrc owner=dfn group=dfn state=link
  - name: Installing wget
    apt: pkg=wget update_cache=yes
